# Generated by Django 6.0.4 on 2026-05-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
