# Generated by Django 6.0.4 on 2026-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_add_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
