# Generated by Django 6.0.4 on 2026-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_add_goal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='allocation_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Percentage of available savings to allocate (0-100)'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Goal is still being funded'),
        ),
    ]
