# Generated by Django 6.0.4 on 2026-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_add_goal_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='last_allocated_month',
            field=models.CharField(blank=True, default='', help_text="YYYY-MM of the last month allocation was applied, e.g. '2025-05'", max_length=7),
        ),
    ]
