# Generated by Django 6.0.4 on 2026-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_excessincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='current_month_auto_allocation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-allocation currently applied for the active month', max_digits=12),
        ),
    ]
