# Generated by Django 6.0.4 on 2026-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_savingsgoal_current_month_auto_allocation'),
    ]

    operations = []
