# Generated by Django 6.0.4 on 2026-05-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_add_current_month_auto_allocation'),
    ]

    operations = []
    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='current_month_auto_allocation',
        ),
    ]
