# Generated by Django 6.0.4 on 2026-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_savingsgoal_current_month_auto_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='current_month_auto_allocation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-allocation for current month (reversible)', max_digits=12),
        ),
    ]
