# Generated by Codex on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0017_pageview_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("transport", "Transport"),
                    ("health", "Health"),
                    ("groceries", "Groceries"),
                    ("entertainment", "Entertainment"),
                    ("shopping", "Shopping"),
                    ("food", "Food"),
                    ("utilities", "Utilities"),
                    ("lend", "Lend"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_settled",
            field=models.BooleanField(
                default=False,
                help_text="Marks lending transactions as paid back.",
            ),
        ),
    ]
