# Generated by Django 6.0.4 on 2026-08-17 08:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_transaction_lend_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAnalysisMailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Send monthly analysis emails automatically.')),
                ('send_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month to send. Use 1 for the first day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('send_time', models.TimeField(default=datetime.time(9, 0), help_text='Local time to send the monthly analysis.')),
                ('last_sent_month', models.CharField(blank=True, default='', help_text='YYYY-MM report month last sent by the scheduled command.', max_length=7)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Analysis Mail Setting',
                'verbose_name_plural': 'Monthly Analysis Mail Settings',
            },
        ),
    ]
