# Generated by Django 6.0.4 on 2026-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_monthlyanalysismailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
