# Generated by Django 6.0.4 on 2026-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_userprofile_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('inr', '₹ INR'), ('usd', '$ USD')], default='inr', max_length=5),
        ),
    ]
