# Generated by Django 6.0.4 on 2026-09-27 17:59

from django.db import migrations, models


def clear_legacy_otp_codes(apps, schema_editor):
    UserProfile = apps.get_model('login', 'UserProfile')
    UserProfile.objects.filter(email_verification_code__regex=r'^\d{5,}$').update(
        email_verification_code='',
    )
    UserProfile.objects.filter(password_reset_code__regex=r'^\d{5,}$').update(
        password_reset_code='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_userprofile_currency'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_otp_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
