# Generated by Django 6.0.4 on 2026-09-29 06:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_userprofile_email_verification_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyanalysismailsetting',
            options={'verbose_name': 'Monthly Email Schedule', 'verbose_name_plural': 'Monthly Email Schedule'},
        ),
        migrations.AlterField(
            model_name='monthlyanalysismailsetting',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Turn automatic monthly report emails on or off.'),
        ),
        migrations.AlterField(
            model_name='monthlyanalysismailsetting',
            name='send_day',
            field=models.PositiveSmallIntegerField(default=1, help_text="Choose a day from 1 to 28. Automatic emails contain the previous completed month's report.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='monthlyanalysismailsetting',
            name='send_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Send time in Asia/Kolkata.'),
        ),
        migrations.CreateModel(
            name='OfficeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('taken', 'Taken'), ('came', 'Came From')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
