# Generated by Django 6.0.4 on 2026-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_monthlyanalysismailsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeentry',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Person or source this movement relates to.', max_length=80),
        ),
    ]
