# Generated by Django 6.0.4 on 2026-09-29 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_officeentry_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='officeentry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='Date this movement belongs to.'),
        ),
    ]
