# Generated by Django 6.0.4 on 2026-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_officeentry_options_officeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeentry',
            name='direction',
            field=models.CharField(choices=[('taken', 'Money Out'), ('came', 'Money In')], max_length=5),
        ),
        migrations.AlterField(
            model_name='officeentry',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Person who sent (money in) or received (money out) it.', max_length=80),
        ),
    ]
