# Generated by Django 6.0.4 on 2026-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_extra_monthly_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyanalysismailsetting',
            name='last_sent_month_day8',
            field=models.CharField(blank=True, default='', help_text='YYYY-MM last sent by the 8th schedule.', max_length=7),
        ),
        migrations.AlterField(
            model_name='monthlyanalysismailsetting',
            name='send_day_8_enabled',
            field=models.BooleanField(default=False, help_text='Also send on 8th of the month at 00:00 IST.'),
        ),
    ]
