"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import importlib.util
from pathlib import Path
from urllib.parse import parse_qs, urlparse, unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str) -> list[str]:
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]


def database_config() -> dict:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if database_url:
        parsed = urlparse(database_url)
        query = parse_qs(parsed.query)
        scheme = (parsed.scheme or '').lower()
        if scheme in {'postgres', 'postgresql', 'pgsql'}:
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote((parsed.path or '/').lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or 'localhost',
                'PORT': str(parsed.port or '5432'),
                'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
                'OPTIONS': {
                    **({'sslmode': query.get('sslmode', ['require'])[0]} if parsed.hostname and parsed.hostname != 'localhost' else {}),
                },
            }

        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote((parsed.path or '/').lstrip('/')),
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or 'localhost',
            'PORT': str(parsed.port or '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                **({'sslmode': query.get('sslmode', ['require'])[0]} if parsed.hostname and parsed.hostname != 'localhost' else {}),
            },
        }

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', os.getenv('POSTGRES_DB', 'spendwise')),
        'USER': os.getenv('DB_USER', os.getenv('POSTGRES_USER', 'postgres')),
        'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('POSTGRES_PASSWORD', 'postgres')),
        'HOST': os.getenv('DB_HOST', os.getenv('POSTGRES_HOST', 'localhost')),
        'PORT': os.getenv('DB_PORT', os.getenv('POSTGRES_PORT', '5432')),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        'OPTIONS': {
            **({'sslmode': os.getenv('DB_SSLMODE', 'prefer')} if os.getenv('DB_HOST', os.getenv('POSTGRES_HOST', 'localhost')) not in {'localhost', '127.0.0.1'} else {}),
        },
    }


WHITENOISE_ENABLED = os.getenv('USE_WHITENOISE', '1') == '1' and importlib.util.find_spec('whitenoise') is not None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dbr@s354m68v)cd&tsl0z5u-r$35dg)t*uc5*#t9)p%a=gvj0g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = list(dict.fromkeys([
    "127.0.0.1",
    "localhost",
    "testserver",
    ".ngrok-free.app",
    ".ngrok.io",
    ".ngrok-free.dev",
    "dispersed-stump-retype.ngrok-free.dev",
    "0.0.0.0",
    ".onrender.com",
    *env_list('ALLOWED_HOSTS'),
]))

# Allow ngrok forwarded headers
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
    "https://*.ngrok-free.dev",
    "https://dispersed-stump-retype.ngrok-free.dev",
]
render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_external_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_external_hostname}')
CSRF_TRUSTED_ORIGINS.extend(env_list('CSRF_TRUSTED_ORIGINS'))


# Application definition

INSTALLED_APPS = [
    "unfold",            
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    *(['whitenoise.middleware.WhiteNoiseMiddleware'] if WHITENOISE_ENABLED else []),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

UNFOLD = {
    "SITE_TITLE": "My Admin",
    "SITE_HEADER": "My Dashboard",
    "SITE_SYMBOL": "dashboard",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': database_config()
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
if WHITENOISE_ENABLED:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)

MAILTRAP_SMTP_HOST = os.getenv('MAILTRAP_SMTP_HOST', 'live.smtp.mailtrap.io').strip()
MAILTRAP_SMTP_PORT = int(os.getenv('MAILTRAP_SMTP_PORT', '587'))
MAILTRAP_SMTP_USER = os.getenv('MAILTRAP_SMTP_USER', '').strip()
MAILTRAP_SMTP_PASSWORD = os.getenv('MAILTRAP_SMTP_PASSWORD', '').strip()
MAILTRAP_FROM_EMAIL = os.getenv('MAILTRAP_FROM_EMAIL', '').strip()

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if MAILTRAP_SMTP_USER and MAILTRAP_SMTP_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = MAILTRAP_SMTP_HOST
EMAIL_PORT = MAILTRAP_SMTP_PORT
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = MAILTRAP_SMTP_USER
EMAIL_HOST_PASSWORD = MAILTRAP_SMTP_PASSWORD
EMAIL_TIMEOUT = 20
DEFAULT_FROM_EMAIL = (
    MAILTRAP_FROM_EMAIL
    if MAILTRAP_FROM_EMAIL else
    'SpendWise <no-reply@spendwise.local>'
)
EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES = 10

# OpenAI (optional): used for dashboard savings motivation message generation.
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '').strip()
OPENAI_MOTIVATION_MODEL = os.getenv('OPENAI_MOTIVATION_MODEL', 'gpt-4.1-mini').strip()
